---
title: "Farsr package How-to"
author: "Vladimir Semitchev"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
knitr::opts_knit$set(root.dir = file.path(find.package("farsr"),"extdata"))
library(farsr)
library(maps)
```
farsr package can be used in mutiple ways

### First, to load the data from a CSV report file downloaded from FARS to a dataframe

```{r eval=FALSE}
df <- fars_read(system.file("extdata","accident_2014.csv.bz2",package="farsr"))
```

### Second, to load the FARS report data for multiple years


```{r eval=FALSE}
mon_year <- fars_read_years(c(2013,2014,2015))
```

### Third, to generate a summary report for each month of each year from the list of years.

```{r eval=FALSE}
fars_summarize_years(c(2014,2015))
```
```{r, echo=FALSE, results='asis'}
knitr::kable(fars_summarize_years(c(2014,2015)))
```

### Finally, it can generate a map of the give state showing location of each accident

```{r}
fars_map_state(6,2015)
```

